# Generated by Django 3.0 on 2021-01-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
