# Generated by Django 3.0 on 2021-01-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210104_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='img',
            new_name='myfile',
        ),
    ]
