# Generated by Django 3.0 on 2021-01-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210104_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='myfile',
            field=models.FileField(upload_to='upload'),
        ),
    ]
