# Generated by Django 3.0 on 2021-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210106_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
